import React, { useRef } from 'react';
import { SEMANTIC_COLORS } from '@/types/smartLayout';
import type { LayoutZone, SmartLayoutAsset } from '@/types/smartLayout';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { X, Upload, Trash2 } from 'lucide-react';

interface ConfigPanelProps {
  zone: LayoutZone | null;
  onChange: (updatedZone: LayoutZone) => void;
  onClose: () => void;
  onDelete: () => void;
  canvasSize?: { width: number; height: number };
  allZones?: LayoutZone[];
  onAutoGenerateDepthTree?: () => void;
  layout?: 'overlay' | 'inline';
  className?: string;
  assets?: SmartLayoutAsset[];
  onAddAsset?: (asset: { name: string; dataUrl: string }) => string;
}

export const ConfigPanel: React.FC<ConfigPanelProps> = ({ zone, onChange, onClose, onDelete, canvasSize = { width: 800, height: 800 }, allZones = [], onAutoGenerateDepthTree, layout = 'overlay', className, assets = [], onAddAsset }) => {
  const fileInputRef = useRef<HTMLInputElement>(null);

  if (!zone) return null;

  const x = Math.round(zone.x);
  const y = Math.round(zone.y);
  const w = Math.round(zone.width);
  const h = Math.round(zone.height);

  const cx = x + w / 2;
  const cy = y + h / 2;
  const col = cx < (canvasSize.width / 3) ? 'Left' : cx < (canvasSize.width * 2 / 3) ? 'Center' : 'Right';
  const row = cy < (canvasSize.height / 3) ? 'Top' : cy < (canvasSize.height * 2 / 3) ? 'Center' : 'Bottom';
  const locationHint = `${row}-${col}`;
  const currentRefImageSrc = zone.refImageId
    ? assets.find(a => a.id === zone.refImageId)?.dataUrl
    : zone.refImage;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        if (event.target?.result) {
          const dataUrl = event.target.result as string;
          const refImageId = onAddAsset ? onAddAsset({ name: file.name, dataUrl }) : undefined;
          const typeLabel = zone.type === 'background' ? '背景' : zone.type === 'prop' ? '道具' : '主体';
          onChange({ 
            ...zone, 
            refImageId,
            refImage: refImageId ? undefined : dataUrl,
            autoCaption: `自动描述（Mock）：${typeLabel}参考图，文件名 ${file.name}`,
          });
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const handleInsertAutoCaption = () => {
    const autoCaption = zone.autoCaption?.trim();
    if (!autoCaption) return;
    const currentPrompt = (zone.prompt || '').trim();
    if (!currentPrompt) {
      onChange({ ...zone, prompt: autoCaption });
      return;
    }
    if (currentPrompt.includes(autoCaption)) {
      return;
    }
    onChange({ ...zone, prompt: `${currentPrompt}，${autoCaption}` });
  };

  return (
    <div
      className={[
        layout === 'overlay'
          ? 'w-80 bg-[#14141a] border-l border-white/10 p-4 flex flex-col gap-6 h-full shadow-xl z-10 absolute right-0 top-0 bottom-0 overflow-y-auto'
          : 'w-full bg-[#14141a] p-4 flex flex-col gap-6 h-full overflow-y-auto',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <div className="flex justify-between items-center">
        <h3 className="font-semibold text-lg text-white">区域配置</h3>
        <Button variant="ghost" size="icon" onClick={onClose} className="text-white/60 hover:text-white hover:bg-white/10">
          <X className="h-4 w-4" />
        </Button>
      </div>

      <div className="space-y-4">
        {/* Type Selection */}
        <div className="space-y-2">
          <Label className="text-white/80">区域类型</Label>
          <Select 
            value={zone.type} 
            onValueChange={(value) => onChange({ 
              ...zone, 
              type: value as any,
              semanticColor: SEMANTIC_COLORS[value as keyof typeof SEMANTIC_COLORS],
            })}
          >
            <SelectTrigger className="bg-white/5 border-white/10 text-white">
              <SelectValue placeholder="选择类型" />
            </SelectTrigger>
            <SelectContent className="bg-[#1c1c21] border-white/10 text-white">
              <SelectItem value="background" className="focus:bg-white/10 focus:text-white">背景层</SelectItem>
              <SelectItem value="prop" className="focus:bg-white/10 focus:text-white">道具层</SelectItem>
              <SelectItem value="main" className="focus:bg-white/10 focus:text-white">主体层</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-white/80">锁定图层</Label>
            <Switch
              checked={zone.locked === true}
              onCheckedChange={(checked) => onChange({ ...zone, locked: checked })}
            />
          </div>
          <div className="text-xs text-white/40">
            锁定后不可拖拽/缩放；开启画框模式或按住 Shift 仍可在其上新建区域。
          </div>
        </div>

        {/* Prompt Input */}
        <div className="space-y-2">
          <Label className="text-white/80">提示词描述</Label>
          <Textarea 
            placeholder="描述该区域的内容..." 
            value={zone.prompt || ''}
            onChange={(e) => onChange({ ...zone, prompt: e.target.value })}
            className="min-h-[100px] bg-white/5 border-white/10 text-white placeholder:text-white/30"
          />
        </div>

        {/* Auto Caption */}
        <div className="space-y-2">
          <Label className="text-white/80">自动描述</Label>
          <div className="rounded-md border border-white/10 bg-white/5 px-3 py-2 text-xs text-white/70 whitespace-pre-wrap">
            {zone.autoCaption ? zone.autoCaption : '上传参考图片后自动生成（Mock）'}
          </div>
          <Button
            variant="outline"
            size="sm"
            className="w-full border-white/10 text-white/70 hover:text-white hover:bg-white/10 disabled:opacity-40"
            onClick={handleInsertAutoCaption}
            disabled={!zone.autoCaption}
          >
            插入自动描述
          </Button>
        </div>

        {/* Reference Image Upload */}
        <div className="space-y-2">
          <Label className="text-white/80">参考图片</Label>
          <div 
            className="border-2 border-dashed border-white/10 rounded-lg p-4 flex flex-col items-center justify-center cursor-pointer hover:border-white/20 transition-colors bg-white/5"
            onClick={() => fileInputRef.current?.click()}
          >
            {currentRefImageSrc ? (
              <div className="relative w-full aspect-square group">
                <img src={currentRefImageSrc} alt="Reference" className="w-full h-full object-contain rounded-md" />
                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center rounded-md">
                   <span className="text-white text-xs">点击更换</span>
                </div>
              </div>
            ) : (
              <>
                <Upload className="h-8 w-8 text-white/40 mb-2" />
                <span className="text-xs text-white/40">上传图片</span>
              </>
            )}
            <input 
              ref={fileInputRef}
              type="file" 
              accept="image/*" 
              className="hidden" 
              onChange={handleFileChange}
            />
          </div>
          <div className="flex items-center gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="outline"
                  size="sm"
                  className="flex-1 border-white/10 text-white/70 hover:text-white hover:bg-white/10 disabled:opacity-40"
                  disabled={assets.length === 0}
                >
                  从素材库选择
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="bg-[#1c1c21] border-white/10 text-white max-h-[360px] overflow-auto w-[260px]">
                {assets
                  .slice()
                  .sort((a, b) => b.createdAt - a.createdAt)
                  .map((a) => (
                    <DropdownMenuItem
                      key={a.id}
                      onSelect={() => onChange({ ...zone, refImageId: a.id, refImage: undefined })}
                      className="focus:bg-white/10 focus:text-white"
                    >
                      <div className="flex items-center gap-2 w-full">
                        <div className="w-9 h-9 rounded-md overflow-hidden border border-white/10 bg-white/5 shrink-0">
                          <img src={a.dataUrl} alt={a.name} className="w-full h-full object-cover" />
                        </div>
                        <div className="text-xs text-white/80 truncate flex-1">{a.name}</div>
                      </div>
                    </DropdownMenuItem>
                  ))}
              </DropdownMenuContent>
            </DropdownMenu>
            <Button
              variant="outline"
              size="sm"
              className="border-red-500/30 text-red-400 hover:text-red-300 hover:bg-red-500/10 disabled:opacity-40"
              disabled={!currentRefImageSrc}
              onClick={() => onChange({ ...zone, refImageId: undefined, refImage: undefined, autoCaption: undefined })}
            >
              移除
            </Button>
          </div>
        </div>

        {/* Z-Index Control (Optional but useful) */}
        <div className="space-y-2">
           <Label className="text-white/80">图层顺序</Label>
           <div className="flex items-center gap-2">
             <Button 
               variant="outline" 
               size="sm" 
               className="border-white/10 text-white/70 hover:text-white hover:bg-white/10"
               onClick={() => onChange({ ...zone, zIndex: Math.max(0, zone.zIndex - 1) })}
             >
               后移一层
             </Button>
             <span className="flex-1 text-center text-sm font-mono text-white">{zone.zIndex}</span>
             <Button 
               variant="outline" 
               size="sm" 
               className="border-white/10 text-white/70 hover:text-white hover:bg-white/10"
               onClick={() => onChange({ ...zone, zIndex: zone.zIndex + 1 })}
             >
               前移一层
             </Button>
           </div>
        </div>

        {/* Coordinates Hint */}
        <div className="space-y-2">
          <Label className="text-white/80">坐标信息（px）</Label>
          <div className="rounded-md border border-white/10 bg-white/5 px-3 py-2 text-xs text-white/70">
            <div className="flex items-center justify-between gap-2">
              <span className="text-white/50">x, y</span>
              <span className="font-mono">{x}, {y}</span>
            </div>
            <div className="flex items-center justify-between gap-2 mt-1">
              <span className="text-white/50">w × h</span>
              <span className="font-mono">{w} × {h}</span>
            </div>
            <div className="flex items-center justify-between gap-2 mt-1">
              <span className="text-white/50">locationHint</span>
              <span className="font-mono">{locationHint}</span>
            </div>
            <div className="flex items-center justify-between gap-2 mt-1">
              <span className="text-white/50">sketchColor</span>
              <span className="font-mono flex items-center gap-2">
                <span className="inline-block w-3 h-3 rounded-sm border border-white/20" style={{ backgroundColor: zone.sketchColor || zone.semanticColor }} />
                {zone.sketchColor || zone.semanticColor}
              </span>
            </div>
          </div>
        </div>

        {/* Depth / Occlusion */}
        <div className="space-y-2">
          <div className="flex items-center justify-between gap-2">
            <Label className="text-white/80">遮挡关系（覆盖对象）</Label>
            <Button
              variant="outline"
              size="sm"
              className="h-8 border-white/10 text-white/70 hover:text-white hover:bg-white/10"
              onClick={() => onAutoGenerateDepthTree?.()}
              disabled={!onAutoGenerateDepthTree}
            >
              按 zIndex 自动生成遮挡树
            </Button>
          </div>

          <div className="space-y-2">
            {allZones.filter(z => z.id !== zone.id).length === 0 ? (
              <div className="text-xs text-white/50">暂无其他区域</div>
            ) : (
              allZones
                .filter(z => z.id !== zone.id)
                .sort((a, b) => a.zIndex - b.zIndex)
                .map(z => {
                  const checked = (zone.coveredZoneIds || []).includes(z.id);
                  return (
                    <label key={z.id} className="flex items-center justify-between gap-3 rounded-md border border-white/10 bg-white/5 px-3 py-2">
                      <span className="text-xs text-white/80 truncate">
                        {z.prompt?.trim() ? z.prompt.trim() : (z.type === 'background' ? '背景' : z.type === 'prop' ? '道具' : '主体')}（z={z.zIndex}）
                      </span>
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={(e) => {
                          const next = new Set(zone.coveredZoneIds || []);
                          if (e.target.checked) {
                            next.add(z.id);
                          } else {
                            next.delete(z.id);
                          }
                          onChange({ ...zone, coveredZoneIds: Array.from(next) });
                        }}
                        className="h-4 w-4"
                      />
                    </label>
                  );
                })
            )}
          </div>
        </div>

        <div className="pt-4 border-t border-white/10">
           <Button variant="destructive" className="w-full" onClick={onDelete}>
             <Trash2 className="mr-2 h-4 w-4" />
             删除区域
           </Button>
        </div>
      </div>
    </div>
  );
};
